name: Desktop Browsers Tests - 2

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '00 3 * * *'
  workflow_dispatch:

jobs:
  browser:
    name: Run Browser-based Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macOS-12 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up Native Selenium Grid
        if: runner.os == 'Linux'
        run: docker-compose -f GUI_Web/src/main/resources/docker-compose/selenium4.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Check running containers
        if: runner.os == 'Linux'
        run: docker ps
      - name: Run tests on Linux/MacOS
        if: runner.os != 'Windows'
        continue-on-error: true
        run: |
          cd GUI_Web/
          if [ "$RUNNER_OS" == "Linux" ]; then
               mvn test -DsuiteXmlFile="testng.xml" -DexecutionAddress="localhost:4444" -DtargetOperatingSystem="Linux-64" -DmaximumPerformanceMode="2" -DtargetBrowserName="GoogleChrome" -DgenerateAllureReportArchive="true" 
          elif [ "$RUNNER_OS" == "macOS" ]; then
               mvn test -DsuiteXmlFile="testng.xml" -DexecutionAddress="browserstack" -DtargetOperatingSystem="Mac-64" -DmaximumPerformanceMode="1" -DtargetBrowserName="Safari" "-DbrowserStack.os=OS X" "-DbrowserStack.osVersion=Monterey" "-DbrowserStack.browserVersion=15.3" -DgenerateAllureReportArchive="true" 
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
      - name: Run tests on Windows
        if: runner.os == 'Windows'
        continue-on-error: true
        run: |
          cd GUI_Web/
          mvn test -DsuiteXmlFile="testng.xml" -DexecutionAddress="local" -DtargetOperatingSystem="Windows-64" -DmaximumPerformanceMode="2" -DtargetBrowserName="MicrosoftEdge" -DgenerateAllureReportArchive="true" 
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Allure Report
          path: "GUI_Web/generatedReport_*.zip"

      - name: Upload Extent Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Extent Report
          path: "GUI_Web/extent-reports/ExtentReports_*.html"
